### ISSUE TITLE
Ubuntu Cantera Install with conda..

### ISSUE THREAD

**Issue by rddaz2013** [Cantera/cantera#461] opened 2017-06-30 16:39 UTC
### Cantera version
newest

### Operating System
Ubuntu

### Python/MATLAB version
Anaconda Python 2.7

### Expected Behavior
Install Cantera within the conda env

### Actual Behavior
UnsatisfiableError: The following specifications were found to be in conflict:
  - cantera
  - enable

> platform : linux-64
>           conda version : 4.3.22
>        conda is private : False
>       conda-env version : 4.3.22
>     conda-build version : 2.1.16
>          python version : 2.7.13.final.0
>        requests version : 2.14.2
> 
>            channel URLs : https://repo.continuum.io/pkgs/free/linux-64
>                           https://repo.continuum.io/pkgs/free/noarch
>                           https://repo.continuum.io/pkgs/r/linux-64
>                           https://repo.continuum.io/pkgs/r/noarch
>                           https://repo.continuum.io/pkgs/pro/linux-64
>                           https://repo.continuum.io/pkgs/pro/noarch
>             config file : None
>              netrc file : None
>            offline mode : False
>              user-agent : conda/4.3.22 requests/2.14.2 CPython/2.7.13 Linux/4.4.0-81-generic debian/stretch/sid glibc/2.23

### Steps to reproduce
1. conda install -c cantera cantera 

? conda issues or recipe of cantera

**Comment by bryanwweber** [comment] 2017-07-01 03:53
It seems likely that you have installed the `enable` package which requires an old version of NumPy that is not included in our Cantera builds. You can either

1. Uninstall the `enable` package or
2. Build the Cantera package yourself for the version of numpy that you have installed. If you would like help building the Cantera package, please post on the Cantera User Group: https://groups.google.com/forum/#!forum/cantera-users

Please let us know if either of these solutions doesn't work.

**Comment by rddaz2013** [comment] 2017-07-01 08:03
mhh thx for the quick answer.

I would not have come from the error message to the cause numpy...but which version of numpy cantera need or with which is our conda package build?

**Comment by bryanwweber** [comment] 2017-07-01 15:18
Cantera is currently built with NumPy 1.11, 1.12, and 1.13. However, we are pretty sure Cantera will work with versions of NumPy going back to 1.6, except that 1.8 is broken. You'll just have to build Cantera yourself if you need to use the older version of NumPy 😄 

By the way, I guessed that this the cause because I checked

    conda info enable

and saw the NumPy versions they built for (on macOS, but I assume the same on Ubuntu) are the older versions.

**Comment by bryanwweber** [comment] 2017-07-07 01:12
@rddaz2013 Are there any changes we need to make to Cantera to resolve this issue?

**Comment by rddaz2013** [comment] 2017-07-07 18:35
srry much to do...

I think the conda meta.yaml needs a update in the 'Run' section.

```
requirements:
  | build:
  | - python >=2.7,<3|>=3.3,{{PY_VER}}*
  | - **numpy >=1.8,{{NPY_VER}}***
  | - mkl # [linux]
  | run:
  | - python {{PY_VER}}*
  | - **numpy {{NPY_VER}}***
  | - mkl # [linux]
  | - vs2015_runtime # [win]
```
from https://github.com/Cantera/conda-recipes/blob/master/cantera/meta.yaml

perhaps it is better in both sections (build,run) 
**numpy >=1.9,{{NPY_VER}}**

that means cantera could be run with numpy 1.9 to 1.13
or better only **numpy >=1.9**

**Comment by bryanwweber** [comment] 2017-07-09 02:52
Unfortunately, the `{{NPY_VER}}` is required because Cantera is built against a specific version of numpy, trying to use a package built against numpy 1.13 would not work with numpy 1.9 for instance because of possible ABI differences in the numpy library. We only build for the most recent versions of numpy because we have only limited free space on the anaconda.org servers and most people don't need really old versions of numpy. If you want those older versions, it's not too difficult to build yourself.

**Comment by bryanwweber** [comment] 2017-07-09 02:53
Also, is there a specific reason you want to bump the minimum numpy version to 1.9?

**Comment by rddaz2013** [comment] 2017-07-09 07:00
see you own post .-)

> Cantera is currently built with NumPy 1.11, 1.12, and 1.13. However, we are pretty sure Cantera will work with versions of NumPy going back to 1.6, except that 1.8 is broken...

**Comment by bryanwweber** [comment] 2017-07-09 12:29
We haven't actually specifically figured out which versions fail, so we haven't changed that number :smiley: Can you file an issue on that repo so I remember to fix it? Thanks! I'm going to close this now, since it seems like an issue with the recipe specifically and not with Cantera generally

**Closed as completed by bryanwweber** 2017-07-09 12:29 UTC

**Comment by bryanwweber** [comment] 2017-07-09 12:30
See also: https://github.com/Cantera/cantera/issues/445
