### ISSUE TITLE
'NotImplementedError: Solution object is not picklable'

### ISSUE THREAD

**Issue by AlexGiorgini** [Cantera/cantera#623] opened 2019-04-15 20:24 UTC
### Cantera version
2.4.0
### Operating System
Windows 10
### Python/MATLAB version
Python 2.7.16

Hi everyone,

i'm writing here in order to understand how to manage the exception raised by the code, specifically 'NotImplementedError: Solution object is not picklable'. I'm not an expert of Cantera and i've been given the code in the context of my master thesis in order to analyze it for future applications in the field of internal combustion engines (the code deals with the modeling of a combustion reaction in an homogeneous reactor at constant pressure in order to study the autoignition of different fuel mixtures).  I think that the issue is related to the behaviour of multiprocessing module on Windows with respect to Linux, in fact the code is working on Ubuntu 18.04. I've read the issue #205  and also the commit in order to solve it but to be honest i don't know how to find the file base.pyx and if it is enough to fix something on it (which is cited in the traceback given by the code). For the installation of Cantera i've followed the Windows install instructions, not the Compile cantera from source section.

Thanks in advance for the attention and sorry for my inexperience about the Cantera tool.

Best regards,

Alex Giorgini

**Comment by bryanwweber** [comment] 2019-04-15 22:32
Hi @AlexGiorgini! Welcome to Cantera. The Google Users Group is the appropriate place for this post. Unfortunately, we also need to you please include a minimal sample script with your post that demonstrates the error you're getting. If you could make a new post over on Google with this content and an example, that would be fantastic. Thank you!

**Comment by speth** [comment] 2019-04-16 20:50
Duplicate of #570.

**Closed as completed by speth** 2019-04-16 20:50 UTC
