### ISSUE TITLE
Installation on platforms with disk quotas in /tmp

### ISSUE THREAD

**Issue by santoshshanbhogue** [Cantera/cantera#1260] opened 2022-04-29 17:59 UTC
**Problem description**
When building/installing cantera on a cluster I get an error messages saying "disk quota exceeded" even though I have ample space

**Steps to reproduce**

This error happens twice. once during the build and second during the installation. Testing is not affected 

`scons build`
`scons install`

**Behavior**

Building wheels for collected packages: Cantera
  Running command /home/gridsan/sshanbhogue/.conda/envs/default/bin/python /home/gridsan/sshanbhogue/.conda/envs/default/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpwhl8yy_r
  running bdist_wheel
  running build
  running build_py
  running egg_info
  writing Cantera.egg-info/PKG-INFO
  writing dependency_links to Cantera.egg-info/dependency_links.txt
  writing entry points to Cantera.egg-info/entry_points.txt
  writing requirements to Cantera.egg-info/requires.txt
  writing top-level names to Cantera.egg-info/top_level.txt
  reading manifest file 'Cantera.egg-info/SOURCES.txt'
  adding license file 'LICENSE.txt'
  writing manifest file 'Cantera.egg-info/SOURCES.txt'
  running build_ext
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.linux-x86_64/wheel
  creating build/bdist.linux-x86_64/wheel/cantera
  copying build/lib.linux-x86_64-3.9/cantera/__init__.py -> build/bdist.linux-x86_64/wheel/cantera
  copying build/lib.linux-x86_64-3.9/cantera/_cantera.cpython-39-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/wheel/cantera
  error: could not write to 'build/bdist.linux-x86_64/wheel/cantera/_cantera.cpython-39-x86_64-linux-gnu.so': Disk quota exceeded
  Building wheel for Cantera (PEP 517) ... error
  ERROR: Failed building wheel for Cantera
Failed to build Cantera
ERROR: Could not build wheels for Cantera which use PEP 517 and cannot be installed directly
scons: *** [build/python/dummy] Error 1
scons: building terminated because of errors.

**System information**

- Cantera version: 08602cd97 (i.e. the one with the tag 2.6)
- OS: Ubuntu 18.04.6 LTS
- Python/MATLAB/other software versions: Python 3.9

**Attachments**

I did these simple changes to work around this problem for now:

https://github.com/santoshshanbhogue/cantera/commit/d6975568b1f6cb967fbce662d0b8a6ca258f616a

While researching the problem, it seems that setting the environment variable `$TMPDIR` should direct `pip` to not use `/tmp` but this does not work for cantera. Scons keeps defaulting to using `/tmp`

**Additional context**

**Comment by bryanwweber** [comment] 2022-04-29 18:08
By default, SCons does not pass through environment variables so that builds are reproducible across platforms. If you want to pass through that variable, you need to assign it to the `env_vars` config option:

```
scons build env_vars=TMPDIR
```

Second, why are you building Cantera on the cluster? It looks like you're using a conda environment, why not use the conda packages? Or the system packages from `apt`?

Finally, I think it's reasonable to add that flag to the `pip` command regardless of the cause; it will resolve a warning on older `pip`s that I don't hit because I tend to keep pip up-to-date. Please feel free to make a pull request to add that option 😄

**Comment by santoshshanbhogue** [comment] 2022-04-29 18:50
Thanks! the `env_vars` option fixes it. I've also submitted a pull request 

re. why not use Conda/apt - I like to test the latest features. Hence my preference for building from source 

Thanks again

**Closed as completed** 2022-04-29 18:51 UTC
