### ISSUE TITLE
Order of `extra` columns in SolutionArray is not preserved

### ISSUE THREAD

**Issue by ischoegl** [Cantera/cantera#832] opened 2020-03-27 22:19 UTC
**System information**

- Cantera version: 2.5.0a4 (and earlier?)
- OS: Ubuntu Xenial (16.04)
- Python/MATLAB version: Python 3.5.2

**Expected behavior**

`SolutionArray.write_csv` writes `extra` columns in correct order regardless of OS / Python version.

**Actual behavior**

Some columns are swapped for some OS / Python versions.

**To Reproduce**

```
In [1]: import cantera as ct
  ... : gas = ct.Solution('h2o2.yaml')
  ... : arr = ct.SolutionArray(gas, 10, extra={'grid': range(10), 'velocity': range(10)})

In [2]: arr._extra
Out[2]: 
{'velocity': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 'grid': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]}

In [3]: arr.write_csv('test.csv')

In [4]: !head test.csv --lines=3
velocity,grid,T,density,Y_H2,Y_H,Y_O,Y_O2,Y_OH,Y_H2O,Y_HO2,Y_H2O2,Y_AR
0.0,0.0,300.0,0.081893927638,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1.0,1.0,300.0,0.081893927638,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
```

**Thoughts:**

* This is obviously linked to Python dictionaries not (necessarily) preserving order
* An option that preserves an `OrderedDict` would require a tweak of internal storage, where the following should result in the expected behavior:
```python
arr = ct.SolutionArray(gas, 10, extra=OrderedDict([('grid', range(10)), 
                                                   ('velocity', range(10))]))
```

**Comment by bryanwweber** [comment] 2020-03-27 23:00
This seems really minor, does this impact performance or other behavior in any way? Aside from that, this will be resolved with Python 3.6, if I recall correctly.

**Comment by ischoegl** [comment] 2020-03-27 23:15
It is minor but affects Travis and pre Python 3.6 installations. Further, #305 proposes to write 1D results via `SolutionArray` extra columns to CSV, which would create consistent (and re-importable) output, with the caveat that the column order may not be preserved.

**Comment by bryanwweber** [comment] 2020-03-29 02:33
@ischoegl I'm not sure I understand your comment. If a header row is given in the CSV, why does the order matter? I don't see what the practical effect of fixing this would be. Furthermore, the title of the issue is that column order is not preserved, but then you state "with the caveat that column order may not be preserved". Can you clarify? Thanks.

**Comment by ischoegl** [comment] 2020-03-29 03:17
@bryanwweber Xenial builds do not preserve order, newer builds do (which caused some issues for failing unit tests that were not easily tracked down). 

I believe that you're correct that the behavior depends on the Python version. I agree that header rows would still allow for a correct identification, but I'd rather ensure that the CSV output of a 1D `FlameBase` object has the `grid` column first *always* (see #805 or the code sample given above). Of course, the relevance of this depends on the fate of #805; I simply thought that the PR was already getting too long so I didn't want to add it there.

A potential fix is simple: use an `OrderedDict` internally, so if there's an `OrderedDict` passed as an argument, the order is preserved. Otherwise, the column order follows the dictionary item order. As long as Python < 3.6 is supported, I believe it's worthwhile to address this 'paper cut'.

**Closed as completed** 2020-06-05 22:04 UTC
