### ISSUE TITLE
Cantera 2.3.0 dislikes RMG's element list

### ISSUE THREAD

**Issue by alongd** [Cantera/cantera#361] opened 2016-08-17 17:59 UTC
I couldn't get Cantera v. 2.3.0a3 to work with any RMG-generated models, until I tried to delete all elements from the element list that weren't related to any of the model species (i.e., Si, S, Cl).
I didn't have to delete He or Ne, which were defined as species, yet not used (well, He was used in the collider efficiencies, but Ne wasn't used at all in my model).
Cantera v. 2.2.0 did work smooth with RMG models. We'll try to address this in RMG-Py (see https://github.com/ReactionMechanismGenerator/RMG-Py/issues/748) and make RMG models more robust, but it would also be great if Cantera would once again be able to ignore elements in the element list of an input file if those don't constitutes any species.

**Comment by speth** [comment] 2016-08-17 19:07
What does "dislike" mean? What exactly goes wrong? Can you provide an example?

**Comment by alongd** [comment] 2016-08-17 21:46
Sure, sorry for that. I get:

```
File "cantera\onedim.pyx", line 678, in cantera._cantera.Sim1D.solve (interfaces\cython\cantera\_cantera.cpp:69578)
Exception: 
***********************************************************************
CanteraError thrown by MultiNewton::step:
Jacobian is singular for domain flame, component u at point 0
(Matrix row 2) 
see file bandmatrix.csv
***********************************************************************
```

and it runs smoothly if I only remove these extra species from the input file.

[bandmatrix.csv.txt](https://github.com/Cantera/cantera/files/423648/bandmatrix.csv.txt)

**Comment by alongd** [comment] 2016-08-17 21:49
I attach the input files of a small mechanism as an example. The 'original' one has the extra species and causes the error, the 'modified' one runs.
[xo1173R(modified).cti.txt](https://github.com/Cantera/cantera/files/423688/xo1173R.modified.cti.txt)
[xo1173R(original).cti.txt](https://github.com/Cantera/cantera/files/423687/xo1173R.original.cti.txt)

**Comment by speth** [comment] 2016-08-18 01:55
When I tried the "original" file, I encountered some problems with `equilibrate` that turned out to be a regression since Cantera 2.2.0. This bug is fixed in 0bd88927.

With that fixed, I am able to run a slightly-modified version of the `adiabatic_flame.py` example successfully. If this version doesn't resolve your problem, please post a script that demonstrates the problem, not just the mechanism file.

**Comment by alongd** [comment] 2016-08-23 14:10
Thanks, I still couldn't get the original model to work.
I'm using the [twin_premixed_flame_axisymmetric.ipynb](https://github.com/Cantera/cantera-jupyter/blob/master/flames/twin_premixed_flame_axisymmetric.ipynb)

**Comment by santoshshanbhogue** [comment] 2016-08-23 15:06
@alongd I have seen this problem in commercial solvers as well. The way I work around this is by adding a trivial amount of a species, say 10e-10 or so, to prevent a singular Jacobian. So in your case, have a look at the Jacobian and identify the column with all zeros. If it is Cl, add 10e-8 or so of Cl. Not as solution, but a fix to get moving...

**Comment by alongd** [comment] 2016-08-23 15:09
Thanks @santoshshanbhogue !
For now I deleted the elements from the element list that don't show up at all in the species list.

**Comment by speth** [comment] 2016-08-29 03:38
I am not able to replicate this problem using 0bd8892, the provided CTI file, and `twin_premixed_flame_axisymmetric.ipynb` with the initial mixture set as:

``` python
gas.set_equivalence_ratio(0.75, 'CH4(1)', {'O2(2)':1.0, 'N2':3.76})
```

Can you please provide a _complete_ example that demonstrates the problem?

**Comment by alongd** [comment] 2016-09-02 12:42
You are right, I don't see the problem using 0bd88927f5e0703277390c94e3dafedd24391b3c. Thanks for your help!

**Closed as completed** 2016-09-02 12:43 UTC
