### ISSUE TITLE
Segmentation fault while reading a YAML file in C++

### ISSUE THREAD

**Issue by gkogekar** [Cantera/cantera#1237] opened 2022-04-04 16:44 UTC
**Problem description**

Cantera crashes when a YAML file is read in C++.  A call to `newSolution` gives a segmentation fault error. 

**Steps to reproduce**

1. Compile and run the attached canteraYAML.cpp file. 
2. The program crashes if mech.yaml file is read. 
3. If reactions 11 and 15 are deleted/commented, then the program reads the input mechanism successfully.

**System information**

- Cantera version: Cantera's current build (also tried on the build downloaded in February.)
- OS: Windows 10

**Attachments**
[YAML_read.zip](https://github.com/Cantera/cantera/files/8411575/YAML_read.zip)

**Comment by ischoegl** [comment] 2022-04-04 16:55
Thanks for submitting this issue!

I tried loading this in Python and get several unmarked duplicates
```
CanteraError: 
*******************************************************************************
InputFileError thrown by Kinetics::checkDuplicates:
Error on lines 307 and 311 of ./mech.yaml:
Undeclared duplicate reactions detected:
Reaction 11: 2 H + M <=> H2 + M
Reaction 10: 2 H + O2 <=> H2 + O2

|  Line |
|   302 |   duplicate: true
|   303 |   rate-constant: {A: 2.83e+13, b: -0.764, Ea: -460.3}
|   304 | - equation: OH + OH <=> O + H2O  # Reaction 9
|   305 |   duplicate: true
|   306 |   rate-constant: {A: 1.26e+04, b: 2.531, Ea: -1622.0}
>   307 > - equation: H + H + M <=> H2 + M  # Reaction 10
            ^
|   308 |   type: three-body
|   309 |   rate-constant: {A: 1.0e+18, b: -1.0, Ea: 0.0}
|   310 |   efficiencies: {H2O: 0.0, H2: 0.0, CO2: 0.0}
>   311 > - equation: H + H + O2 <=> H2 + O2  # Reaction 11
            ^
|   312 |   rate-constant: {A: 8.69e+20, b: -1.23, Ea: 0.0}
|   313 | - equation: H + H + O2 <=> OH + OH  # Reaction 12
|   314 |   rate-constant: {A: 8.69e+20, b: -1.23, Ea: 0.0}
*******************************************************************************
```
(plus another pair: reactions 15 and 13). Once I fix this, the mechanism loads in Python without issues. 

Could you see whether you can replicate the segfault with a mechanism that does not contain duplicates? That way, we may be able to narrow down at what point things go wrong.

*(Edit: referencing #1092)*

**Comment by gkogekar** [comment] 2022-04-04 17:13
Thanks for checking it in Python. I deleted the duplicates now, but I am still getting the same segmentation fault. I think the error is present only on the C++ side, since we are able to run this mechanism using Python pfr model.

**Comment by ischoegl** [comment] 2022-04-04 17:25
> I think the error is present only on the C++ side

Recent Cantera builds use the same import routines for C++ and Python, so there shouldn't be any/much difference in behavior.

**Comment by speth** [comment] 2022-04-04 17:26
Do you have a minimal C++ program that demonstrates the error?

**Comment by ischoegl** [comment] 2022-04-04 17:26
> Do you have a minimal C++ program that demonstrates the error?

It's part of the zip'd archive on top (which I haven't checked yet as my hunch was that something may have gone awry with the error messages)

**Comment by speth** [comment] 2022-04-04 17:32
Ah, sorry, I missed that. I think the problem is that the exception thrown by `newSolution` is just being allowed to escape. If you try the following, I think it will show you the same message as @ischoegl posted above.
```cxx
using namespace std;
#include <iostream>
//Include Cantera files
#include "cantera/base/Solution.h"

using namespace Cantera;

int main()
{
    try {
        auto sol = newSolution("mech.yaml", "gas", "");
        cout << "Successfully read the mechanism" << endl;
    } catch (CanteraError& err) {
        cout << err.what() << endl;
    }
}
```

**Comment by ischoegl** [comment] 2022-04-04 17:39
@speth ... fwiw, most examples don't include that block, but should? Also, the [very simple C++ program](https://cantera.org/tutorials/cxx-guide/simple-example.html) should probably be updated?

**Comment by ischoegl** [comment] 2022-04-04 21:14
@gkogekar ... On Fedora 35, I get

```
(cantera-dev) [ischoegl@FC35 demo]$ g++ canteraYAML.cpp -o canteraYAML $(pkg-config --cflags --libs cantera)
(cantera-dev) [ischoegl@FC35 demo]$ ./canteraYAML 
terminate called after throwing an instance of 'Cantera::InputFileError'
  what():  
*******************************************************************************
InputFileError thrown by Kinetics::checkDuplicates:
Error on lines 307 and 311 of ./mech.yaml:
Undeclared duplicate reactions detected:
Reaction 11: 2 H + M <=> H2 + M
Reaction 10: 2 H + O2 <=> H2 + O2

|  Line |
|   302 |   duplicate: true
|   303 |   rate-constant: {A: 2.83e+13, b: -0.764, Ea: -460.3}
|   304 | - equation: OH + OH <=> O + H2O  # Reaction 9
|   305 |   duplicate: true
|   306 |   rate-constant: {A: 1.26e+04, b: 2.531, Ea: -1622.0}
>   307 > - equation: H + H + M <=> H2 + M  # Reaction 10
            ^
|   308 |   type: three-body
|   309 |   rate-constant: {A: 1.0e+18, b: -1.0, Ea: 0.0}
|   310 |   efficiencies: {H2O: 0.0, H2: 0.0, CO2: 0.0}
>   311 > - equation: H + H + O2 <=> H2 + O2  # Reaction 11
            ^
|   312 |   rate-constant: {A: 8.69e+20, b: -1.23, Ea: 0.0}
|   313 | - equation: H + H + O2 <=> OH + OH  # Reaction 12
|   314 |   rate-constant: {A: 8.69e+20, b: -1.23, Ea: 0.0}
*******************************************************************************

Aborted (core dumped)
```
for the original file with duplicate reactions, but
```
(cantera-dev) [ischoegl@FC35 demo]$ g++ canteraYAML.cpp -o canteraYAML $(pkg-config --cflags --libs cantera)
(cantera-dev) [ischoegl@FC35 demo]$ ./canteraYAML 
Successfully read the mechanism(cantera-dev) [ischoegl@FC35 demo]$ 
```
once I declare the duplicate reactions.

So I believe @speth's diagnosis is correct.

**Comment by bryanwweber** [comment] 2022-04-05 17:42
Can we wait for @gkogekar to confirm the fix before closing?

Also, IMO, a segfault is suboptimal even if the error isn't caught. Is there an improvement we can make here, or is this a limitation of C++ programs? I'm not familiar enough to know.

**Comment by ischoegl** [comment] 2022-04-05 18:05
@bryanwweber ... fair point about the segfault, but this is likely a question for @speth.

**Comment by gkogekar** [comment] 2022-04-05 19:29
The error is gone after declaring the duplicate reactions. Thanks.

**Closed as completed** 2022-04-05 19:29 UTC

**Comment by speth** [comment] 2022-04-06 02:14
There is not much library code like Cantera can or should do. An unhandled exception results in a call to [`std::terminate`](https://en.cppreference.com/w/cpp/error/terminate). There are some ways of affecting the behavior of `std::terminate` does, but I don't think there's a good way to decide which library being used by a user's program should set that. I think the preferable option is to write programs that have a `try`/`catch` block in their `main` function, as we show in most of our examples.
