### ISSUE TITLE
'KineticsAddSpecies.add_species_sequential' test failed

### ISSUE THREAD

**Issue by sagitter** [Cantera/cantera#367] opened 2016-10-15 11:56 UTC
Hello.

`KineticsAddSpecies.add_species_sequential` is failed with these errors:

```
[ RUN      ] KineticsAddSpecies.add_species_sequential
test/kinetics/kineticsFromScratch.cpp:427: Failure
Value of: w[i]
  Actual: 217.99038879671906
Expected: w_ref[iref]
Which is: 217.99038879671923
sp = H2O2; N = 4
test/kinetics/kineticsFromScratch.cpp:427: Failure
Value of: w[i]
  Actual: 248034692.62737739
Expected: w_ref[iref]
Which is: 248034692.62737754
sp = H2; N = 5
test/kinetics/kineticsFromScratch.cpp:427: Failure
Value of: w[i]
  Actual: 248033565.55450577
Expected: w_ref[iref]
Which is: 248033565.55450591
sp = O2; N = 5
[  FAILED  ] KineticsAddSpecies.add_species_sequential (130 ms)
```

Full log: https://kojipkgs.fedoraproject.org//work/tasks/2418/16092418/build.log

`Cantera` is built on a Enterprise Linux 7 system (Fedora, [EPEL7](https://fedoraproject.org/wiki/EPEL)), PowerPC64le architecture with this software: https://kojipkgs.fedoraproject.org//work/tasks/2418/16092418/root.log

**Comment by speth** [comment] 2016-10-15 17:53
This may be a bit challenging to fix, since this error doesn't occur on any of the platforms where I regularly compile Cantera, and I don't have access to a machine that uses the POWER8 architecture. This isn't a test where I would expect platform-specific failures -- the set of actual rate calculations done for each half of the comparison should be identical, and I'm hesitant to just allow an inexact comparison here without digging into it a bit.

I modified the test cases to make some additional checks. If you can provide the output of running the test suite for the current version (50d0f99), it might help a bit. Some other information that would be helpful:
- What other platforms/architectures are packages being built for, and are there any issues with any of them?
- Has the test suite been running successfully previously on this platform? If so, can you identify the commit where the test started failing?
- How are these builds being run? Is this automated off of Github/master, or are they triggered manually? Are the build logs for all platforms available? Is there a way to trigger builds for a branch or PR (i.e. without making new commits to `master`)?

**Comment by sagitter** [comment] 2016-10-16 16:54
Let me do some tests.

**Comment by speth** [comment] 2016-12-18 03:58
@sagitter Unless you can provide some more details about this, I'm inclined to close this bug on the basis of it being unreproducible.

**Closed as completed** 2017-01-19 03:38 UTC
