### ISSUE TITLE
addReaction produce two different copy of the rate object

### ISSUE THREAD

**Issue by BangShiuh** [Cantera/cantera#1811] opened 2024-11-10 23:27 UTC
**Problem description**

The below code prints the address of rate objects.

    void add(size_t rxn_index, ReactionRate& rate) override {
        m_indices[rxn_index] = m_rxn_rates.size();
        m_rxn_rates.emplace_back(rxn_index, dynamic_cast<RateType&>(rate));
        // Print the address of 'rate' and the address of the corresponding element in m_rxn_rates
        std::cout << "Address of rate: " << &rate << std::endl;
        std::cout << "Address of element in m_rxn_rates: " << &m_rxn_rates.back().second << std::endl;
        m_shared.invalidateCache();
    }

It shows that the address is different. This creates issues:

    Extra memory to store rate data
    Change of Reaction::rate() does not affect the corresponding element in m_rxn_rates.

This "add" function is called by BulkKinetics::addReaction,

    // Add reaction rate to evaluator
    size_t index = m_bulk_types[rtype];
    m_bulk_rates[index]->add(nReactions() - 1, *rate);

**Steps to reproduce**

1. Add the print to the source code and compile
2. Initiate a solution object (with reactions)
3. See the printed address

**Behavior**

**System information**

- Cantera version: 3.1

**Attachments**

**Additional context**

**Comment by ischoegl** [comment] 2024-11-11 00:53
@BangShiuh this is by design … see #1211 and related discussions.

This is overall a long-standing design choice. There were some discussions on this topic a couple of years ago that were never revisited. Closing this as it is not a ‘bug’. Feel free to open an enhancement request that acknowledges the existing design choices and proposes a consolidated approach.

**Closed as completed by ischoegl** 2024-11-11 00:53 UTC
