### ISSUE TITLE
 ImportError: libmkl_rt.so.2 in anaconda env

### ISSUE THREAD

**Issue by ProfLeao** [Cantera/cantera#1391] opened 2022-09-16 18:47 UTC
Hello guys.
I'm getting the following error when trying to import cantera.
```
In [2]: import cantera as ct
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Input In [2], in <cell line: 1>()
----> 1 import cantera as ct

File ~/anaconda3/envs/ct-env/lib/python3.9/site-packages/cantera/__init__.py:4, in <module>
      1 # This file is part of Cantera. See License.txt in the top-level directory or
      2 # at https://cantera.org/license.txt for license and copyright information.
----> 4 from ._cantera import *
      5 from ._cantera import __version__, __sundials_version__, __git_commit__
      6 from .composite import *

ImportError: libmkl_rt.so.2: cannot open shared object file: No such file or directory
```
I installed it in anaconda environment with: 
```
conda create --name ct-env --channel cantera cantera ipython matplotlib jupyter
```

and my system is:
```
Linux reginaldo-gesesc 5.15.0-47-generic #51-Ubuntu SMP Thu Aug 11 07:51:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

Could someone help me?

**Comment by bryanwweber** [comment] 2022-09-16 19:43
This looks like a duplicate of https://github.com/Cantera/conda-recipes/issues/29, please feel free to reopen if it's not. Thanks!

**Closed as completed** 2022-09-16 19:43 UTC

**Comment by ProfLeao** [comment] 2022-09-16 19:49
> This looks like a duplicate of [Cantera/conda-recipes#29](https://github.com/Cantera/conda-recipes/issues/29), please feel free to reopen if it's not. Thanks!

Sorry! In my intense workflow, I completely forgot about the previous issue, which I noticed in another context.

**Comment by bryanwweber** [comment] 2022-09-16 21:01
No problem ☺️
