### ISSUE TITLE
Build fails with libfmt-10.0.0

### ISSUE THREAD

**Issue by yurivict** [Cantera/cantera#1556] opened 2023-07-28 16:54 UTC
**Problem description**
```
In file included from src/base/AnyMap.cpp:1:
In file included from /wrkdirs/usr/ports/science/cantera/work/cantera-2.6.0/src/pch/system.h:17:
In file included from include/cantera/base/fmt.h:17:
In file included from /usr/local/include/fmt/format.h:49:
/usr/local/include/fmt/core.h:1690:3: error: static_assert failed due to requirement 'formattable' "Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt"
  static_assert(
  ^
/usr/local/include/fmt/core.h:1711:10: note: in instantiation of function template specialization 'fmt::detail::make_value<fmt::basic_format_context<fmt::appender, char>, const std::__bit_const_reference<std::vector<bool>> &>' requested here
  return make_value<Context>(val);
         ^
/usr/local/include/fmt/core.h:1825:23: note: in instantiation of function template specialization 'fmt::detail::make_arg<true, fmt::basic_format_context<fmt::appender, char>, fmt::detail::type::custom_type, const std::__bit_const_reference<std::vector<bool>> &, 0>' requested here
        data_{detail::make_arg<
                      ^
```

**System information**

- Cantera version: 2.6.0
- clang-15
- OS: FreeBSD 13.2

**Comment by ischoegl** [comment] 2023-07-28 17:04
Duplicate of #1537. Fixed in #1538 for Cantera 3.0. There won't be a backport for 2.6: please pin fmt to an earlier version.

**Closed as completed by ischoegl** 2023-07-28 17:04 UTC
